var limitnum = 10;
var baseUrl = "http://localhost:8762";
var login ="/login";
var uploadJar="/user/uploadPlJar";
var getAppList="/user/getAppList";
var getAppApiList="/user/getAppApiList";
var deleteAppnet="/user/deleteApp";
var updateAppStats="/user/updateAppStats";
var getServerNodes="/user/getservernodes";
var getFliters = "/user/getfliters";
var deleteFliters = "/user/deletefliters";
var updateFiitersStat = "/user/updateflitersStat";
var getConfinglist = "/user/getConfigs";
var addConfig = "/user/addConfig"
var getConnectionPool="/user/getconnectpool";
var delConnectionPool="/user/deleteconnectpool";
var statConnectionPool="/user/statconnectpool";
