#端口
server:
  port: 8762

spring:
  application:
    name: freenet-service-user

  #数据库链接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java_box?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wangyang

  #redis 配置
  redis:
    database: 5
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      # 连接池中的最大空闲连接，默认值也是8。
      max-idle: 500
      #连接池中的最小空闲连接，默认值也是0。
      min-idle: 50
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 1000
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-active: 2000
  http:
    multipart:
      max-file-size: 1000mb
      max-request-size: 1000mb
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
mybatis:
  type-aliases-package: com.freenet.entity

